/// Flutter icons DrawerIconFile
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DrawerIconFile
///      fonts:
///       - asset: fonts/DrawerIconFile.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DrawerIconFile {
  DrawerIconFile._();

  static const _kFontFam = 'DrawerIconFile';
  static const String? _kFontPkg = null;

  static const IconData contactUs =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signin =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signup =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aboutus =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
